# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Phonotes' do
  use_frameworks!

  # Pods for Phonotes
  pod 'RealmSwift', '~> 3.16'

  target 'PhonotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhonotesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
